### ISSUE TITLE
Instaling release 1.1.0, /node_module/vue-content-loader seems empty.

### ISSUE THREAD

**Issue by brenohq** [StevenYuysy/vue-content-placeholder#11]
Hello, I tried to install the latest version of your library and I encountered a problem.

When I try to run `npm install --save vue-content-loader` , my /node_modules/vue-content-loader appears empty, causing "Cannot resolve module 'vue-content-loader'".

![image](https://user-images.githubusercontent.com/13019691/30605042-1a491a72-9d43-11e7-8061-adb177f486b8.png)

Solution:
I had to install an older version by running:
`npm install --save vue-content-loader@1.0.6`

and works fine! Thank you bro!

**Comment by StevenYuysy** [comment]
Oh I forgot to build before publishing! 
Apologize for my behavior 😢
Fix in 1.1.1 🙌

![2017-09-20 09 59 45](https://user-images.githubusercontent.com/11738111/30623565-e8b943da-9dea-11e7-9695-a63be5246e6c.png)
