### ISSUE TITLE
CSS Styling ?

### ISSUE THREAD

**Issue by rsouverain-kaliop** [StevenYuysy/vue-content-placeholder#12]
Hello,

Is it possible to change the various colors programatically or via css classes ?

**Comment by StevenYuysy** [comment]
Sure, you can overwrite the css if you like.

**Comment by StevenYuysy** [comment]
If you need this feature, I can make `background` as a property.

**Comment by rsouverain-kaliop** [comment]
Hi,

Feel free to add as much customizable possibilities to this package if you want it to be used.

I ended up making my own content-placeholder based on this one; to be able to
- externalize css outside of the component to be able to use my sass variables for colors
- making prop: "row" optional by adding a default "rows" array within the component,

**Comment by StevenYuysy** [comment]
Thx for your advice, but I am quite busy now. I would be very appreciate if you can have a PR!
