### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by dflourusso** [StevenYuysy/vue-content-placeholder#5]
Could you provide usage examples in the README please?

Thank's

**Comment by StevenYuysy** [comment]
Currently you can see the usage example of this component: https://github.com/StevenYuysy/vue-content-placeholder/blob/gh-pages/src/App.vue

I will add more usage examples in the README ASAP.

**Comment by StevenYuysy** [comment]
d17c75ac850ec738f326919b9ff1874686db478d
