### ISSUE TITLE
Container class and animated-backgroup-size

### ISSUE THREAD

**Issue by murilolopes** [StevenYuysy/vue-content-placeholder#7]
I think is better remove the container class and make this dev responsibility. Because in my case i don't need this class and i think also is a good idea can set animated-background-size with a prop in component. Can useful?

**Comment by StevenYuysy** [comment]
Yeah, actually I am working on it.

**Comment by StevenYuysy** [comment]
Fixed in ebecddd637807d8afe3da4dea6aaef131198a364
